**** PROPERTIES SKAFFOLDER ****
{
    "forEachObj": "oneTime",
    "_partials": []
}
**** END PROPERTIES SKAFFOLDER ****
# Create image based on the official Node 6 image from dockerhub
FROM nginx

# Create a directory where our app will be placed
ADD ./ /usr/share/nginx/html

# Expose the port the app runs in
EXPOSE 80
